global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['prometheus:9090']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - aboutfacehawaii.dermpro.com
      - advanceddermclinic.dermpro.com
      - advancederm.dermpro.com
      - aestheticsolutions.dermpro.com
      - agelessjax.dermpro.com
      - agelessmed.dermpro.com
      - alabamaderm.dermpro.com
      - alexandriaderm.dermpro.com
      - aloeskinandbody.dermpro.com
      - anewyouskinbodyclinic.dermpro.com
      - antonaesthetics.dermpro.com
      - apexdermatology.dermpro.com
      - arvivaesthetics.dermpro.com
      - auralaser.dermpro.com
      - austinpsi.dermpro.com
      - azulmedspa.dermpro.com
      - baweightspa.dermpro.com
      - belagecenter.dermpro.com
      - bellabodymedicalspa.dermpro.com
      - birminghamskin.dermpro.com
      - bitarinstitute.dermpro.com
      - blackledgefacecenter.dermpro.com
      - blossommedspa.dermpro.com
      - bodymassagewellnessspa.dermpro.com
      - boydbeauty.dermpro.com
      - brickellcosmetic.dermpro.com
      - buinewiczplasticsurgery.dermpro.com
      - bwderm.dermpro.com
      - centerdermlaser.dermpro.com
      - centraldermcenter.dermpro.com
      - cffbr.dermpro.com
      - charlotteskinandlaser.dermpro.com
      - chevychasedermcenter.dermpro.com
      - cirilloinstitute.dermpro.com
      - contempoaesthetics.dermpro.com
      - coolsculptingalabama.dermpro.com
      - coolsculptingwoodstock.dermpro.com
      - corinthianspa.dermpro.com
      - cosmedoctor.dermpro.com
      - cosmeticsolutionslaser.dermpro.com
      - cpsdocs.dermpro.com
      - csaok.dermpro.com
      - csipd.dermpro.com
      - ctdermgroup.dermpro.com
      - culturamed.dermpro.com
      - dallasassocderm.dermpro.com
      - dallascosmeticderm
      - dallasdermatology.dermpro.com
      - daltonderm.dermpro.com
      - dayglomedspa.dermpro.com
      - deepbluemedspa.dermpro.com
      - dermacaresandiego.dermpro.com
      - dermatologyofeasttexas.dermpro.com
      - dermcarestl.dermpro.com
      - dermntx.dermpro.com
      - dermpartnersbocaraton.dermpro.com
      - dermreston.dermpro.com
      - derrowdermatology.dermpro.com
      - deuamerica.dermpro.com
      - doverskinhealth.dermpro.com
      - drarmandosoto.dermpro.com
      - drbartelsnh.dermpro.com
      - drbaum.dermpro.com
      - drnowak.dermpro.com
      - drpeterkay.dermpro.com
      - drsarahlevy.dermpro.com
      - drsukkar.dermpro.com
      - drsuzanneyee.dermpro.com
      - ecmamedspa.dermpro.com
      - edinaskincare.dermpro.com
      - eternacosmeticsurgery.dermpro.com
      - faceandbodycenterspa.dermpro.com
      - facialaestheticsurgery.dermpro.com
      - feinsteindermatology.dermpro.com
      - foreveryoungwellnessspa.dermpro.com
      - foreviva.dermpro.com
      - glolaserandmedspa.dermpro.com
      - grandpearlspa.dermpro.com
      - greenbergcosmeticsurgery.dermpro.com
      - hallplasticsurgery.dermpro.com
      - hellosmooth.dermpro.com
      - hsdermatology.dermpro.com
      - hullderm.dermpro.com
      - hurwitzcenter.dermpro.com
      - invernessderm.dermpro.com
      - iorioplasticsurgery.dermpro.com
      - jonricedmond.dermpro.com
      - kevinwelchmd.dermpro.com
      - khromdermatology.dermpro.com
      - kucumberskinlounge.dermpro.com
      - labaesthetics.dermpro.com
      - laserlipoandveins.dermpro.com
      - laskyskincenter.dermpro.com
      - lepetitspacharlotte.dermpro.com
      - lexingtonps.dermpro.com
      - livingproofmd.dermpro.com
      - lookandfeelbetter.dermpro.com
      - lowcountryplasticsurgery.dermpro.com
      - luxhhi.dermpro.com
      - madskin.dermpro.com
      - mafficlinics.dermpro.com
      - magnoliamedskin.dermpro.com
      - magnoliapromo.dermpro.com
      - makeoveraesthetics.dermpro.com
      - mariposamedspaokc.dermpro.com
      - mcguinessdermatology.dermpro.com
      - mcleansheperdmd.dermpro.com
      - mdbarrows.dermpro.com
      - mdskinlounge.dermpro.com
      - metairieplasticsurgeons.dermpro.com
      - metroderm.dermpro.com
      - miamiplasticsurgery.dermpro.com
      - mirabellamedspa.dermpro.com
      - mirabilemd.dermpro.com
      - mprsd.dermpro.com
      - musickdermatology.dermpro.com
      - mybeautymd.dermpro.com
      - nashskin.dermpro.com
      - naturalimageoc.dermpro.com
      - naturalrejuvenationmedspa.dermpro.com
      - nawadaplasticsurgery.dermpro.com
      - ncdaskin.dermpro.com
      - neemmedicalspa.dermpro.com
      - norcommd.dermpro.com
      - northshoredermcenter.dermpro.com
      - northtexasderm.dermpro.com
      - northtexasplasticsurgery.dermpro.com
      - nuamedspa.dermpro.com
      - nwgadermatology.dermpro.com
      - ocdermatology.dermpro.com
      - ochsdermatology.dermpro.com
      - ogdenclinic.dermpro.com
      - parkavenuemedicalspa.dermpro.com
      - pattiflintmd.dermpro.com
      - pdskin.dermpro.com
      - petroffcenter.dermpro.com
      - physiciansbeautygroup.dermpro.com
      - physicianscenterforbeauty.dermpro.com
      - pierreskincare.dermpro.com
      - plasticsurgeryofsyracuse.dermpro.com
      - platinumderm.dermpro.com
      - ppderm.dermpro.com
      - ppsclt.dermpro.com
      - prismdermatology.dermpro.com
      - profoundrf.dermpro.com
      - puravidanaples.dermpro.com
      - pvps.dermpro.com
      - railanmd.dermpro.com
      - rapdermbh.dermpro.com
      - revivemedicalspa.dermpro.com
      - richmonddermlaser.dermpro.com
      - rochesterlasercenter.dermpro.com
      - rodgersderm.dermpro.com
      - rrdermatologylaser.dermpro.com
      - sandlakedermatology.dermpro.com
      - seasmedspa.dermpro.com
      - serenitymedspa.dermpro.com
      - shellplasticsurgery.dermpro.com
      - sherylclarkmd.dermpro.com
      - silvertonmd.dermpro.com
      - skinandbodyrefinery
      - skincarephysicians.dermpro.com
      - skinexpert.dermpro.com
      - skinlaser.dermpro.com
      - skinsolutionsdermatology.dermpro.com
      - skinspirit.dermpro.com
      - skinwellnessdermatology.dermpro.com
      - skyedermatology.dermpro.com
      - smithderm.dermpro.com
      - smoothmedspa.dermpro.com
      - snakeriverdermatology.dermpro.com
      - soinederm.dermpro.com
      - southeasterndermatology.dermpro.com
      - southernmarinderm.dermpro.com
      - southlakedermatology.dermpro.com
      - southsidedermatology.dermpro.com
      - sparadiance.dermpro.com
      - suitesixmedspa.dermpro.com
      - summitskinaesthetics.dermpro.com
      - surgeryvp.dermpro.com
      - swanndermatologyesthetics.dermpro.com
      - symmetrymedspa.dermpro.com
      - terezakisgrieshaberdermatology.dermpro.com
      - texasbodysculpting.dermpro.com
      - theaestheticsurgeon.dermpro.com
      - theparkerclinic.dermpro.com
      - theshawcenter.dermpro.com
      - theskininstitute.dermpro.com
      - tlhplasticsurgery.dermpro.com
      - totalskinandbeauty.dermpro.com
      - totalskinhealth.dermpro.com
      - tribecaparkdermatology.dermpro.com
      - tulsasurgicalarts.dermpro.com
      - tuscanspaandsalon.dermpro.com
      - txfaces.dermpro.com
      - unitedderm.dermpro.com
      - vaildermatology.dermpro.com
      - villagedermatology.dermpro.com
      - virginiamohs.dermpro.com
      - visagederm.dermpro.com
      - vivadayspa.dermpro.com
      - walkindermatology.dermpro.com
      - wellsplasticsurgery.dermpro.com
      - weloveskin.dermpro.com
      - weloveskin-staging.dermpro.com
      - westaveplasticsurgery.dermpro.com
      - westfieldmedispa.dermpro.com
      - wimedispa.dermpro.com
      - withdrnicole.dermpro.com
      - woodlandsmedicalaesthetics.dermpro.com
      - xagemedicalspa.dermpro.com
      - zlmedspa.dermpro.com
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter.
