- targets:
  - store.austinpsi.com
  - store.mdskinlounge.com
  - store.serenitymedspa.com
  - store.sherylclarkmd.com
  - store.villagedermatology.net
  - store.lowcountryplasticsurgery.com
  - anewyouclinic.com 
  - hellosmooth.dermpro.com
  - mirabellamedspa.dermpro.com
  - culturamed.dermpro.com
  - coolsculptingwoodstock.dermpro.com
  - southeasterndermatology.dermpro.com
  - virginiamohs.dermpro.com
  - ctdermgroup.dermpro.com
  - apexdermatology.com
  - store.drpeterkay.com 
  - store.metairieplasticsurgeons.com 
  - store.bwderm.com 
  - shoppvps.com 
  - store.texasbodysculpting.com 
  - store.dallascosmeticderm.com 
  - store.birminghamskin.com 
  - store.dermntx.com 
  - store.foreveryoungwellnessspa.com 
  - store.mybeautymd.com 
  - store.austinpsi.com 
  - store.mdskinlounge.com 
  - store.serenitymedspa.com 
  - store.sherylclarkmd.com 
  - store.villagedermatology.net 
  - store.wimedispa.com 
  - store.nawadaplasticsurgery.com 
  - dallasassocderm.com
  - northtexasderm.com
  - auralaser.com
  - store.nuamedspa.com 
  - store.doverskinhealth.com 
  - shop.deepbluemedspa.com 
  - store.hullderm.com 
  - store.nashskin.com 
  - store.ocdermatology.com 
  - store.ochsdermatology.com 
  - drnowak.com
  - store.ppderm.com 
  - store.physicianscenterforbeauty.com 
  - store.sandlakedermatology.com 
  - store.skinlaser.com 
  - store.theskininstitute.com 
  - store.vaildermatology.com 
  - store.antonaesthetics.com 
  - store.aesthetic-solutions.com 
  - shop.revivemedicalspa.com 
  - weloveskinstore.com 
  - store.aloeskinandbody.com 
  - store.centraldermcenter.com 
  - store.summitskinaesthetics.com 
  - store.puravidanaples.com 
  - store.brickellcosmetic.com 
  - shopcirillo.com 
  - store.westaveplasticsurgery.com 
  - store.greenbergcosmeticsurgery.com 
  - store.hsdermatology.com 
  - store.mariposamedspaokc.com 
  - store.miamiplasticsurgery.com 
  - store.visagederm.com 
  - store.neemmedicalspa.com 
  - dermstore.ogdenclinic.com 
  - store.woodlandsmedicalaesthetics.com 
  - store.txfaces.com 
  - store.charlotteskinandlaser.com 
  - www.mydermatologycare.com 
  - store.pdskin.com 
  - store.mafficlinics.com 
  - store.mprsd.com 
  - store.hurwitzcenter.com 
  - store.bitarinstitute.com 
  - store.walkindermatology.com 
  - store.dermpartnersbocaraton.com 
  - store.dermreston.com 
  - store.livingproofmd.com 
  - store.boydbeauty.com 
  - store.advancederm.net 
  - store.advanceddermclinic.com 
  - store.totalskinhealth.com 
  - store.symmetrymedspa.com 
  - store.drsukkar.com 
  - store.centerdermlaser.com 
  - store.arvivaesthetics.com 
  - store.pattiflintmd.com 
  - store.rodgersderm.com 
  - store.drarmandosoto.com 
  - store.agelessjax.com 
  - store.blossommedspa.net 
  - store.chevychasedermatologycenter.com 
  - store.skinexpert.com 
  - store.kucumberskinlounge.com 
  - store.skinwellnessdermatology.com 
  - store.northshoredermatologycenter.com 
  - store.theparkerclinic.com 
  - store.southernmarinderm.com 
  - store.snakeriverdermatology.com 
  - store.naturalimageoc.com 
  - store.cpsdocs.com 
  - store.norcommd.com 
  - store.unitedderm.com 
  - store.csaok.com 
  - store.theshawcenter.com 
  - store.hallplasticsurgery.com 
  - store.rapdermbh.com 
  - store.drbaum.com 
  - store.drsuzanneyee.com 
  - store.dermacaresandiego.com 
  - store.wellsplasticsurgery.com 
  - store.contempoaesthetics.com 
  - store.drsarahlevy.com 
  - store.musickdermatology.com 
  - store.tlhplasticsurgery.com 
  - store.lookandfeelbetter.com 
  - store.grandpearlspa.com 
  - store.csipd.com 
  - store.suitesixmedspa.com 
  - store.rrdermatologylaser.com 
  - store.belagecenter.com 
  - store.mdbarrows.com 
  - store.cosmeticsolutionslaser.com 
  - store.corinthianspa.com 
  - store.ncdaskin.com 
  - store.metroderm.com 
  - store.blackledgefacecenter.com 
  - store.richmonddermatology.com 
  - store.triparkderm.com 
  - madskin.com 
  - labaesthetics.com 
  - store.tuscanspaandsalon.com 
  - store.jonricedmond.com 
  - store.khromdermatology.com 
  - store.totalskinandbeauty.com 
  - store.eternacosmeticsurgery.com 
  - www.westfieldmedispa.com 
  - store.sparadiance.com 
  - store.derrowdermatology.com 
  - store.edinaskincare.com 
  - store.buinewiczplasticsurgery.com 
  - store.prismdermatology.com 
  - store.aboutfacekailua.com 
  - store.glolaserandmedspa.com 
  - store.facialaestheticsurgery.com 
  - store.drbartelsnh.com 
  - store.laserlipoandveins.com 
  - shop.skinspirit.com 
  - store.mcguinessdermatology.com 
  - store.feinsteindermatology.com 
  - store.swanndermatology.com 
  - store.smoothmedspa.com 
  - store.skincarephysicians.net 
  - shop.bodymassagewellnessspa.com 
  - store.daltonderm.com 
  - store.lexingtonps.com 
  - shop.rochesterlasercenter.com 
  - store.foreviva.com 
  - store.naturalrejuvenationmedspa.com 
  - store.parkavenuemedicalspa.com 
  - store.luxhhi.com 
  - store.xagemedicalspa.com 
  - store.alexandriaderm.com 
  - store.terezakisgrieshaberdermatology.com 
  - store.withdrnicole.com 
  - store.zlmedspa.com 
  - store.alabamaderm.com 
  - store.baweightspa.com 
  - store.agelessmed.com 
  - store.northtexasplasticsurgery.com 
  - store.laskyskincenter.com 
  - store.bellabodymedicalspa.com 
  - store.mirabilemd.com 
  - store.shellplasticsurgery.com 
  - store.iorioplasticsurgery.com 
  - store.soinederm.com 
  - store.cffbr.com 
  - store.silvertonmd.com 
  - store.7seasmedspa.com 
  - store.magnoliamedskin.com 
  - store.vivadayspa.com 
  - store.ppsclt.com 
  - store.azul-medspa.com 
  - store.southsidedermatology.com 
  - store.pierreskincare.com 
  - surgeryvp.com 
  - store.plasticsurgeryofsyracuse.com 
  - makeoveraesthetics.com 
  - theaestheticsurgeon.com 
  - skinsolutionsdermatology.com 
  - profoundrf.miami 
  - southlakedermatology.com 
  - dermcarestl.com 
  - ecmamedspa.com 
  - mcleansheperdmd.com 
  - physiciansbeautygroup.com
  - lepetitspacharlotte.com 
  - nwgaderm.com 
  - railanmd.com 
  - skinandbodyrefinery.com 
  - kevinwelchmd.com 
  - deuamerica.com 
